name: build_windows_releases

on:
  push:
    tags:
      - 'v*'
#on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.7

    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: build windows pkg
      run: |
        pyinstaller --onedir --icon "demo\icon.ico" --add-data="demo;demo" --add-data="translation.json;." --add-data="README.md;." --add-data="JAV_HELP.md;." --add-data="JavHelper\templates;JavHelper\templates" --add-data="JavHelper\static;JavHelper\static" --add-data="c:\hostedtoolcache\windows\python\3.7.6\x64\lib\site-packages\cloudscraper;cloudscraper" --hidden-import="js2py" --hidden-import="cloudscraper" --hidden-import="cloudscraper_exception" --exclude-module="FixTk"  --exclude-module="tcl"  --exclude-module="tk"  --exclude-module="_tkinter"  --exclude-module="tkinter"  --exclude-module="Tkinter"  --noconfirm --distpath dist-python  JavHelper\run.py

        7z a -tzip "Jav_OneStop_windows.zip" ".\dist-python\"
        
    - name: Create Windows Release
      id: create_release_windows
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}_windows
        release_name: Release ${{ github.ref }} Windows
        draft: false
        prerelease: false

    - name: Upload Release Asset Windows
      id: upload-release-asset-windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
        asset_path: ./Jav_OneStop_windows.zip
        asset_name: Jav_OneStop_windows.zip
        asset_content_type: application/zip
